// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyProto.proto

#include "MyProto.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace MyPackage {

inline constexpr UserInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : user_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UserInfo::UserInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct UserInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserInfoDefaultTypeInternal() {}
  union {
    UserInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserInfoDefaultTypeInternal _UserInfo_default_instance_;

inline constexpr MsgInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::MyPackage::MsgType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MsgInfo::MsgInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MsgInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MsgInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MsgInfoDefaultTypeInternal() {}
  union {
    MsgInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MsgInfoDefaultTypeInternal _MsgInfo_default_instance_;

inline constexpr ImageInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : comment_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        json_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::int64_t{0}},
        time_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageInfo::ImageInfo(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ImageInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageInfoDefaultTypeInternal() {}
  union {
    ImageInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageInfoDefaultTypeInternal _ImageInfo_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace MyPackage
static ::_pb::Metadata file_level_metadata_MyProto_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MyProto_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_MyProto_2eproto = nullptr;
const ::uint32_t TableStruct_MyProto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::UserInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::UserInfo, _impl_.user_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::MsgInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::MsgInfo, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::MsgInfo, _impl_.msg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _impl_.time_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _impl_.comment_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _impl_.json_),
    PROTOBUF_FIELD_OFFSET(::MyPackage::ImageInfo, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MyPackage::Empty)},
        {8, -1, -1, sizeof(::MyPackage::UserInfo)},
        {17, -1, -1, sizeof(::MyPackage::MsgInfo)},
        {27, -1, -1, sizeof(::MyPackage::ImageInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::MyPackage::_Empty_default_instance_._instance,
    &::MyPackage::_UserInfo_default_instance_._instance,
    &::MyPackage::_MsgInfo_default_instance_._instance,
    &::MyPackage::_ImageInfo_default_instance_._instance,
};
const char descriptor_table_protodef_MyProto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rMyProto.proto\022\tMyPackage\"\007\n\005Empty\"\030\n\010U"
    "serInfo\022\014\n\004user\030\001 \001(\t\"8\n\007MsgInfo\022 \n\004type"
    "\030\001 \001(\0162\022.MyPackage.MsgType\022\013\n\003msg\030\002 \001(\t\""
    "R\n\tImageInfo\022\n\n\002id\030\001 \001(\003\022\014\n\004time\030\002 \001(\003\022\017"
    "\n\007comment\030\003 \001(\t\022\014\n\004json\030\004 \001(\t\022\014\n\004data\030\005 "
    "\001(\014*e\n\007MsgType\022\n\n\006TipMsg\020\000\022\022\n\016InsertImag"
    "eMsg\020\001\022\022\n\016DeleteImageMsg\020\002\022\022\n\016UpdateImag"
    "eMsg\020\003\022\022\n\016SelectImageMsg\020\0042\220\003\n\010MyServer\022"
    ".\n\005login\022\023.MyPackage.UserInfo\032\020.MyPackag"
    "e.Empty\022/\n\006logout\022\023.MyPackage.UserInfo\032\020"
    ".MyPackage.Empty\0227\n\013syncMessage\022\022.MyPack"
    "age.MsgInfo\032\022.MyPackage.MsgInfo0\001\0229\n\013ins"
    "ertImage\022\024.MyPackage.ImageInfo\032\024.MyPacka"
    "ge.ImageInfo\0229\n\013deleteImage\022\024.MyPackage."
    "ImageInfo\032\024.MyPackage.ImageInfo\0229\n\013updat"
    "eImage\022\024.MyPackage.ImageInfo\032\024.MyPackage"
    ".ImageInfo\0229\n\013selectImage\022\024.MyPackage.Im"
    "ageInfo\032\024.MyPackage.ImageInfob\006proto3"
};
static ::absl::once_flag descriptor_table_MyProto_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MyProto_2eproto = {
    false,
    false,
    717,
    descriptor_table_protodef_MyProto_2eproto,
    "MyProto.proto",
    &descriptor_table_MyProto_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_MyProto_2eproto::offsets,
    file_level_metadata_MyProto_2eproto,
    file_level_enum_descriptors_MyProto_2eproto,
    file_level_service_descriptors_MyProto_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MyProto_2eproto_getter() {
  return &descriptor_table_MyProto_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MyProto_2eproto(&descriptor_table_MyProto_2eproto);
namespace MyPackage {
const ::google::protobuf::EnumDescriptor* MsgType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MyProto_2eproto);
  return file_level_enum_descriptors_MyProto_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgType_internal_data_[] = {
    327680u, 0u, };
bool MsgType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:MyPackage.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:MyPackage.Empty)
}









::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[0]);
}
// ===================================================================

class UserInfo::_Internal {
 public:
};

UserInfo::UserInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.UserInfo)
}
inline PROTOBUF_NDEBUG_INLINE UserInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : user_(arena, from.user_),
        _cached_size_{0} {}

UserInfo::UserInfo(
    ::google::protobuf::Arena* arena,
    const UserInfo& from)
    : ::google::protobuf::Message(arena) {
  UserInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:MyPackage.UserInfo)
}
inline PROTOBUF_NDEBUG_INLINE UserInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : user_(arena),
        _cached_size_{0} {}

inline void UserInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
UserInfo::~UserInfo() {
  // @@protoc_insertion_point(destructor:MyPackage.UserInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void UserInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.user_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void UserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.UserInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* UserInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 31, 2> UserInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_UserInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string user = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.user_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string user = 1;
    {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.user_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\4\0\0\0\0\0\0"
    "MyPackage.UserInfo"
    "user"
  }},
};

::uint8_t* UserInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.UserInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string user = 1;
  if (!this->_internal_user().empty()) {
    const std::string& _s = this->_internal_user();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.UserInfo.user");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.UserInfo)
  return target;
}

::size_t UserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.UserInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string user = 1;
  if (!this->_internal_user().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_user());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData UserInfo::_class_data_ = {
    UserInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* UserInfo::GetClassData() const {
  return &_class_data_;
}

void UserInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<UserInfo*>(&to_msg);
  auto& from = static_cast<const UserInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.UserInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_user().empty()) {
    _this->_internal_set_user(from._internal_user());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserInfo::CopyFrom(const UserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.UserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool UserInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* UserInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void UserInfo::InternalSwap(UserInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.user_, &other->_impl_.user_, arena);
}

::google::protobuf::Metadata UserInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[1]);
}
// ===================================================================

class MsgInfo::_Internal {
 public:
};

MsgInfo::MsgInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.MsgInfo)
}
inline PROTOBUF_NDEBUG_INLINE MsgInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

MsgInfo::MsgInfo(
    ::google::protobuf::Arena* arena,
    const MsgInfo& from)
    : ::google::protobuf::Message(arena) {
  MsgInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.type_ = from._impl_.type_;

  // @@protoc_insertion_point(copy_constructor:MyPackage.MsgInfo)
}
inline PROTOBUF_NDEBUG_INLINE MsgInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void MsgInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.type_ = {};
}
MsgInfo::~MsgInfo() {
  // @@protoc_insertion_point(destructor:MyPackage.MsgInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MsgInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MsgInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.MsgInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.type_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MsgInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 29, 2> MsgInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MsgInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MsgInfo, _impl_.msg_)}},
    // .MyPackage.MsgType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MsgInfo, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MsgInfo, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MyPackage.MsgType type = 1;
    {PROTOBUF_FIELD_OFFSET(MsgInfo, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(MsgInfo, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\3\0\0\0\0\0"
    "MyPackage.MsgInfo"
    "msg"
  }},
};

::uint8_t* MsgInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.MsgInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .MyPackage.MsgType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    const std::string& _s = this->_internal_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.MsgInfo.msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.MsgInfo)
  return target;
}

::size_t MsgInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.MsgInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 2;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  // .MyPackage.MsgType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MsgInfo::_class_data_ = {
    MsgInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MsgInfo::GetClassData() const {
  return &_class_data_;
}

void MsgInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MsgInfo*>(&to_msg);
  auto& from = static_cast<const MsgInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.MsgInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MsgInfo::CopyFrom(const MsgInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.MsgInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MsgInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MsgInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MsgInfo::InternalSwap(MsgInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  swap(_impl_.type_, other->_impl_.type_);
}

::google::protobuf::Metadata MsgInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[2]);
}
// ===================================================================

class ImageInfo::_Internal {
 public:
};

ImageInfo::ImageInfo(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MyPackage.ImageInfo)
}
inline PROTOBUF_NDEBUG_INLINE ImageInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : comment_(arena, from.comment_),
        json_(arena, from.json_),
        data_(arena, from.data_),
        _cached_size_{0} {}

ImageInfo::ImageInfo(
    ::google::protobuf::Arena* arena,
    const ImageInfo& from)
    : ::google::protobuf::Message(arena) {
  ImageInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, time_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::time_));

  // @@protoc_insertion_point(copy_constructor:MyPackage.ImageInfo)
}
inline PROTOBUF_NDEBUG_INLINE ImageInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : comment_(arena),
        json_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void ImageInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, time_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::time_));
}
ImageInfo::~ImageInfo() {
  // @@protoc_insertion_point(destructor:MyPackage.ImageInfo)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ImageInfo::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.comment_.Destroy();
  _impl_.json_.Destroy();
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ImageInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:MyPackage.ImageInfo)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.comment_.ClearToEmpty();
  _impl_.json_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.time_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.time_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ImageInfo::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 39, 2> ImageInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ImageInfo_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ImageInfo, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.id_)}},
    // int64 time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ImageInfo, _impl_.time_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.time_)}},
    // string comment = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.comment_)}},
    // string json = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.json_)}},
    // bytes data = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.data_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 id = 1;
    {PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 time = 2;
    {PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.time_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // string comment = 3;
    {PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.comment_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string json = 4;
    {PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.json_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 5;
    {PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\0\7\4\0\0\0"
    "MyPackage.ImageInfo"
    "comment"
    "json"
  }},
};

::uint8_t* ImageInfo::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MyPackage.ImageInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_id(), target);
  }

  // int64 time = 2;
  if (this->_internal_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_time(), target);
  }

  // string comment = 3;
  if (!this->_internal_comment().empty()) {
    const std::string& _s = this->_internal_comment();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.ImageInfo.comment");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string json = 4;
  if (!this->_internal_json().empty()) {
    const std::string& _s = this->_internal_json();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MyPackage.ImageInfo.json");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // bytes data = 5;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    target = stream->WriteBytesMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyPackage.ImageInfo)
  return target;
}

::size_t ImageInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyPackage.ImageInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string comment = 3;
  if (!this->_internal_comment().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_comment());
  }

  // string json = 4;
  if (!this->_internal_json().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_json());
  }

  // bytes data = 5;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_data());
  }

  // int64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_id());
  }

  // int64 time = 2;
  if (this->_internal_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ImageInfo::_class_data_ = {
    ImageInfo::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ImageInfo::GetClassData() const {
  return &_class_data_;
}

void ImageInfo::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ImageInfo*>(&to_msg);
  auto& from = static_cast<const ImageInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MyPackage.ImageInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_comment().empty()) {
    _this->_internal_set_comment(from._internal_comment());
  }
  if (!from._internal_json().empty()) {
    _this->_internal_set_json(from._internal_json());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_time() != 0) {
    _this->_internal_set_time(from._internal_time());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageInfo::CopyFrom(const ImageInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyPackage.ImageInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ImageInfo::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ImageInfo::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ImageInfo::InternalSwap(ImageInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.comment_, &other->_impl_.comment_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.json_, &other->_impl_.json_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.time_)
      + sizeof(ImageInfo::_impl_.time_)
      - PROTOBUF_FIELD_OFFSET(ImageInfo, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata ImageInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MyProto_2eproto_getter, &descriptor_table_MyProto_2eproto_once,
      file_level_metadata_MyProto_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace MyPackage
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
